### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by GitLaboratory**

### CODE REVIEW

**Comment by vladislav805** [comment]
What is it? And most importantly, why?

**Comment by GitLaboratory** [comment]
The most universal method, without unnecessary edits of addresses.

**Comment by GitLaboratory** [comment]
It does not affect the work of other extensions.

**Comment by vladislav805** [comment]
This will not affect other sites and extensions, but ... why initiate an extension on other domains at all? At a minimum, why intercept requests to vk.com and replace headers in them, if this is not necessary?

**Pull request closed without merging**
